version: '3'
services:
  cfboom-http:
    build:
      context: .
      args:
        RUN_TESTS: "false"
    image: cfboom/http
    container_name: cfboom-http
    ports:
    - "8888:8888"
    volumes:
    - .:/var/www/modules/cfboom/modules/cfboom-http
